name: Release

permissions: {}

on:
  push:
    tags: ['v6.[0-9]+.[0-9]+']

jobs:
  release:
    permissions:
      actions: read
      contents: write
      discussions: write
      id-token: write
    uses: panva/.github/.github/workflows/npm-release.yml@main
    with:
      artifact_check_command: node tools/test-dist.js "$PACKAGE_TARBALL" .
      cleanup_paths: '["build"]'
      prepare_command: >-
        npm clean-install &&
        npm run build &&
        npm run typecheck:dist &&
        npm run typecheck:types &&
        npm run check:packaging &&
        git diff --exit-code
      publish_jsr: true
